changelog:
  exclude:
    labels:
      - "skip-changelog"
      - "no-release-notes"
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
        - "major"

    - title: "Features"
      labels:
        - "feature"
        - "enhancement"

    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"

    - title: "Dependencies"
      labels:
        - "dependencies"

    - title: "CI / Build"
      labels:
        - "github-actions"
        - "ci"

    - title: "Other Changes"
      labels:
        - "*"

  template: |
    ## Changes
    $CHANGES

    ## Contributors
    $CONTRIBUTORS
